# プラグインを変更/追加した場合は :call dein#update() を実行

#------------------------------------
# dein setting
#------------------------------------
[[plugins]]                                    
repo = 'Shougo/dein.vim'                                          

[[plugins]] # 統合インターフェース
repo   = 'Shougo/unite.vim'

[[plubins]] # 
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

#------------------------------------
# denite setting
#------------------------------------
[[plugins]] # denit
repo = 'Shougo/denite.nvim'                                    
hook_add = '''

    " denite設定呼び出し
    autocmd FileType denite call s:denite_my_settings()
    " denite設定関数
    function! s:denite_my_settings() abort
      nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
      nnoremap <silent><buffer><expr> d denite#do_map('do_action', 'delete')
      nnoremap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
      nnoremap <silent><buffer><expr> q denite#do_map('quit')
      nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
      nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
    endfunction

    " deniteフィルタ設定呼び出し
    autocmd FileType denite-filter call s:denite_filter_my_settings()
    " deniteフィルタ設定関数
    function! s:denite_filter_my_settings() abort
      imap <silent><buffer> <C-o> <Plug>(denite_filter_quit)
    endfunction

    " deniteマッピング
    nnoremap <silent> ,f :<C-u>Denite file/rec<CR>
    nnoremap <silent> ,l :<C-u>Denite line<CR>
    nnoremap <silent> ,g :<C-u>Denite grep<CR>
    nnoremap <silent> ,cg :<C-u>DeniteCursorWord grep<CR>
    nnoremap <silent> ,b : <C-u>Denite buffer<CR>
'''

hook_post_source = '''
    call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

    call denite#custom#source('file_mru', 'matchers', ['matcher/fuzzy', 'matcher/project_files'])
    call denite#custom#source('file/rec', 'matchers', ['matcher/cpsm'])

    call denite#custom#source('file/rec', 'sorters', ['sorter/sublime'])

    call denite#custom#kind('file', 'default_action', 'split')

    call denite#custom#var('grep', {
        \ 'command': ['ag'],
        \ 'default_opts': ['-i', '--vimgrep'],
        \ 'recursive_opts': [],
        \ 'pattern_opt': [],
        \ 'separator': ['--'],
        \ 'final_opts': [],
        \ })

    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])

'''


#------------------------------------
# visual setting plugin
#------------------------------------
[[plugins]] # colorSchem
repo = 'sjl/badwolf'                                    

#------------------------------------
# size setting plugin
#------------------------------------
[[plugins]] # size setting
repo = 'simeji/winresizer'
#https://github.com/simeji/winresizer

#------------------------------------
# markdown setting
#------------------------------------
# [[plugins]] # markdownFromat
# repo = 'tpope/vim-markdown'

[[plugins]] # markdownFormat
repo = "violetyk/iikanji-markdown.vim"

[[plugins]] # markdownTableFormat
repo = 'dhruvasagar/vim-table-mode'
hook_add ='''
    nnoremap <silent> <C-m><C-d> :TableModeToggle<CR>
'''

[[plugins]] # markdownPreview
repo = 'previm/previm'

