# プラグインを変更/追加した場合は :call dein#update() を実行

#------------------------------------
# dein setting
#------------------------------------
[[plugins]]                                    
repo = 'Shougo/dein.vim'                                          

[[plugins]] # 統合インターフェース
repo   = 'Shougo/unite.vim'

[[plubins]] # 
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

#------------------------------------
# denite setting
#------------------------------------
[[plugins]] # denit
repo = 'Shougo/denite.nvim'                                    
hook_add = '''
nmap <silent> ,f :<C-u>Denite file/rec<CR>
nmap <silent> ,l :<C-u>Denite line<CR>
nmap <silent> ,g :<C-u>Denite grep<CR>
nmap <silent> ,cg :<C-u>DeniteCursorWord grep<CR>
'''
hook_post_source = '''
    call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])

    call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
    call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [
      \ '.git/', 'build/', '__pycache__/',
      \ 'images/', '*.o', '*.make',
      \ '*.min.*',
      \ 'img/', 'fonts/'])
'''


#------------------------------------
# visual setting plugin
#------------------------------------
[[plugins]] # colorSchem
repo = 'sjl/badwolf'                                    

#------------------------------------
# size setting plugin
#------------------------------------
[[plugins]] # size setting
repo = 'simeji/winresizer'
#https://github.com/simeji/winresizer

#------------------------------------
# markdown setting
#------------------------------------
# [[plugins]] # markdownFromat
# repo = 'tpope/vim-markdown'

[[plugins]] # markdownFormat
repo = "violetyk/iikanji-markdown.vim"

[[plugins]] # markdownTableFormat
repo = 'dhruvasagar/vim-table-mode'

[[plugins]] # markdownPreview
repo = 'previm/previm'

